In [1]:
import pandas as pd
dataset=pd.read_csv(r"C:\Users\Wow\Downloads\US_Top_50_Universities_2026.csv")

In [2]:
dataset.head()

,University_Name,National_Rank,Founded_Year,Institution_Type,State,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate
0,Massachusetts Institute of Technology (MIT),1,1861,Private,MA,100.0,91.6,96.2
1,Columbia University,2,1754,Private,NY,95.9,83.7,92.1
2,Princeton University,3,1746,Private,NJ,99.0,70.0,94.5
3,Stanford University,4,1891,Private,CA,99.5,73.5,97.8
4,"University of California, Berkeley",5,1868,Public,CA,98.9,70.6,91.4

In [3]:
import numpy as np

In [4]:
dataset_encoded=pd.get_dummies(dataset,columns=["University_Name","Institution_Type","State"])

In [5]:
numeric_cols=dataset_encoded.select_dtypes(include=np.number).columns

In [6]:
basket=dataset_encoded.astype(bool)

In [9]:
from mlxtend.frequent_patterns import apriori, association_rules

In [10]:
frequent_items=apriori(basket,min_support=0.1, use_colnames=True)

In [18]:
rules=association_rules(frequent_items,metric="lift",min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({National_Rank}),frozenset({Founded_Year}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
1,frozenset({Founded_Year}),frozenset({National_Rank}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
2,frozenset({National_Rank}),frozenset({Research_Impact_Score}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
3,frozenset({Research_Impact_Score}),frozenset({National_Rank}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
4,frozenset({National_Rank}),frozenset({Intl_Student_Ratio}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0

In [15]:
import warnings
warnings.filterwarnings("ignore")

In [24]:
rules.sort_values(by="confidence",ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4067,"frozenset({National_Rank, Institution_Type_Pub...","frozenset({Employment_Rate, Founded_Year, Intl...",0.12,1.0,0.12,1.0,1.0,1.0,0.0,inf,0.0,0.12,0.0,0.56
4066,"frozenset({Founded_Year, Institution_Type_Publ...","frozenset({National_Rank, Employment_Rate, Int...",0.12,1.0,0.12,1.0,1.0,1.0,0.0,inf,0.0,0.12,0.0,0.56
4064,"frozenset({Employment_Rate, Institution_Type_P...","frozenset({National_Rank, Founded_Year, Intl_S...",0.12,1.0,0.12,1.0,1.0,1.0,0.0,inf,0.0,0.12,0.0,0.56
31,frozenset({Intl_Student_Ratio}),frozenset({Research_Impact_Score}),1.00,1.0,1.00,1.0,1.0,1.0,0.0,inf,0.0,1.00,0.0,1.00
30,frozenset({Research_Impact_Score}),frozenset({Intl_Student_Ratio}),1.00,1.0,1.00,1.0,1.0,1.0,0.0,inf,0.0,1.00,0.0,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,"frozenset({Founded_Year, Intl_Student_Ratio})","frozenset({Institution_Type_Private, State_CA})",1.00,0.1,0.10,0.1,1.0,1.0,0.0,1.0,0.0,0.10,0.0,0.55
1182,frozenset({Founded_Year}),"frozenset({Institution_Type_Private, State_CA,...",1.00,0.1,0.10,0.1,1.0,1.0,0.0,1.0,0.0,0.10,0.0,0.55
1183,frozenset({Intl_Student_Ratio}),"frozenset({Institution_Type_Private, Founded_Y...",1.00,0.1,0.10,0.1,1.0,1.0,0.0,1.0,0.0,0.10,0.0,0.55
1877,"frozenset({National_Rank, Intl_Student_Ratio})","frozenset({Institution_Type_Private, Founded_Y...",1.00,0.1,0.10,0.1,1.0,1.0,0.0,1.0,0.0,0.10,0.0,0.55
1878,"frozenset({National_Rank, Founded_Year})","frozenset({Institution_Type_Private, State_CA,...",1.00,0.1,0.10,0.1,1.0,1.0,0.0,1.0,0.0,0.10,0.0,0.55

In [22]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({National_Rank}),frozenset({Founded_Year}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
1,frozenset({Founded_Year}),frozenset({National_Rank}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
2,frozenset({National_Rank}),frozenset({Research_Impact_Score}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
3,frozenset({Research_Impact_Score}),frozenset({National_Rank}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0
4,frozenset({National_Rank}),frozenset({Intl_Student_Ratio}),1.0,1.0,1.0,1.0,1.0,1.0,0.0,inf,0.0,1.0,0.0,1.0