In [1]:
import pandas as pd
dataset=pd.read_csv(r"C:\Users\Wow\Downloads\US_Top_50_Universities_2026.csv")

In [2]:
dataset.head()

,University_Name,National_Rank,Founded_Year,Institution_Type,State,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate
0,Massachusetts Institute of Technology (MIT),1,1861,Private,MA,100.0,91.6,96.2
1,Columbia University,2,1754,Private,NY,95.9,83.7,92.1
2,Princeton University,3,1746,Private,NJ,99.0,70.0,94.5
3,Stanford University,4,1891,Private,CA,99.5,73.5,97.8
4,"University of California, Berkeley",5,1868,Public,CA,98.9,70.6,91.4

In [3]:
dataset.tail()

,University_Name,National_Rank,Founded_Year,Institution_Type,State,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate
45,University of Texas at Austin,46,1883,Public,TX,90.1,46.2,89.2
46,Washington and Lee University,47,1749,Private,VA,28.5,4.2,91.5
47,Colgate University,48,1819,Private,NY,30.2,8.4,88.1
48,New York University (NYU),49,1831,Private,NY,94.3,74.1,87.4
49,"University of Washington, Seattle",50,1861,Public,WA,97.6,70.1,85.3

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   University_Name        50 non-null     str
 1   National_Rank          50 non-null     int64
 2   Founded_Year           50 non-null     int64
 3   Institution_Type       50 non-null     str
 4   State                  50 non-null     str
 5   Research_Impact_Score  50 non-null     float64
 6   Intl_Student_Ratio     50 non-null     float64
 7   Employment_Rate        50 non-null     float64
dtypes: float64(3), int64(2), str(3)
memory usage: 4.9 KB

In [5]:
dataset.describe()

,National_Rank,Founded_Year,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate
count,50.00000,50.00000,50.000000,50.000000,50.000000
mean,25.50000,1844.04000,80.662000,44.630000,89.424000
std,14.57738,64.89142,23.380856,31.729985,3.825562
min,1.00000,1636.00000,28.500000,4.200000,81.900000
25%,13.25000,1817.50000,82.100000,14.900000,86.900000
50%,25.50000,1858.50000,89.650000,35.800000,89.300000
75%,37.75000,1884.50000,96.250000,73.950000,92.325000
max,50.00000,1965.00000,100.000000,94.200000,97.800000

In [6]:
dataset=dataset.drop_duplicates()

In [7]:
dataset.isnull().sum()

University_Name          0
National_Rank            0
Founded_Year             0
Institution_Type         0
State                    0
Research_Impact_Score    0
Intl_Student_Ratio       0
Employment_Rate          0
dtype: int64

In [8]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [10]:
dataset_encoded=pd.get_dummies(dataset,columns=["University_Name","Institution_Type","State"])

In [13]:
numeric_cols=dataset_encoded.select_dtypes(include=np.number).columns

In [14]:
scaler=MinMaxScaler()
dataset_encoded[numeric_cols]=scaler.fit_transform(dataset_encoded[numeric_cols])

In [15]:
dataset_encoded.head()

,National_Rank,Founded_Year,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate,University_Name_Amherst College,University_Name_Boston University,University_Name_Bowdoin College,University_Name_Brigham Young University,University_Name_Brown University,...,State_NH,State_NJ,State_NY,State_PA,State_RI,State_TN,State_TX,State_UT,State_VA,State_WA
0,0.000000,0.683891,1.000000,0.971111,0.899371,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0.020408,0.358663,0.942657,0.883333,0.641509,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,0.040816,0.334347,0.986014,0.731111,0.792453,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,0.061224,0.775076,0.993007,0.770000,1.000000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0.081633,0.705167,0.984615,0.737778,0.597484,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False